### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by MonkeyD-Core** [Salmen2/Simple-Faucet-Script#19]
Please tell me wich file i need modif to make this script working for dogecoin ?

**Comment by saadbitcoin** [comment]
A similar mining site needs a mining site that I am preparing on now, but I am a liar and cheated on him by not paying ---- For this reason, I want to create a similar site with the same mining card and have the same links and have the same links. User and everything about mining ----
  What do you recommend ?
  Thank you

**Comment by Salmen2** [comment]
> A similar mining site needs a mining site that I am preparing on now, but I am a liar and cheated on him by not paying ---- For this reason, I want to create a similar site with the same mining card and have the same links and have the same links. User and everything about mining ----
> What do you recommend ?
> Thank you
Pardon but I think this is the wrong page you're looking for. Please draft only related posts to the given issue in the script. This script is in no way affiliated with mining.

> Please tell me wich file i need modif to make this script working for dogecoin ?
Since the script base doesn't contain many files, just replace anything with the keywords "BTC, "Bitcoin" to "DOGE", "Dogecoin".
